name: Backend Main CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "docs/**"


concurrency:
  group: be-main-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # 현재 main commit이 GitHub PR을 통해 merge된 결과인지 확인한다
  check_trigger:
    runs-on: ubuntu-26.04

    permissions:
      contents: read
      pull-requests: read

    outputs:
      run_ci: ${{ steps.check.outputs.run_ci }}

    steps:
      - name: Check Main Push Type
        id: check
        uses: actions/github-script@v9
        with:
          script: |
            const { data: pulls } =
              await github.rest.repos.listPullRequestsAssociatedWithCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                commit_sha: context.sha
              });

            const mergedToMain = pulls.some(
              pr => pr.merged_at && pr.base.ref === 'main'
            );

            core.setOutput('run_ci', mergedToMain ? 'false' : 'true');

  build:
    needs: check_trigger
    if: needs.check_trigger.outputs.run_ci == 'true'

    runs-on: ubuntu-26.04

    permissions:
      contents: read
      id-token: write

    steps:
      # 1. CI Runner에 Repo의 코드를 가져온다
      - name: Checkout
        uses: actions/checkout@v7

      # 2. Java 실행 환경을 구성한다
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      # 3. Gradle 실행 환경을 구성하고 Cache를 사용한다
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      # 4. 컴파일된 Bytecode를 SpotBugs로 정적 분석한다
      - name: SpotBugs
        run: ./gradlew spotbugsMain --build-cache

      # 5. Compile, Test, Package를 수행한다
      - name: Build
        run: ./gradlew build --build-cache

      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to Public ECR
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main'
        env:
          IMAGE_URI: public.ecr.aws/g8x9p1p0/stockspoon-v1-backend:${{ github.sha }}
        run: |
          docker build -t "$IMAGE_URI" .
          docker push "$IMAGE_URI"

      # SpotBugs 검사 실패 시 Report를 남긴다
      - name: Upload SpotBugs report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: build/reports/spotbugs/